// permissions/matrix.ts — the 56 permissions in 10 groups and the exact grant
// set per role (docs/07 §2.1). This is the source the parity script compares
// against the seeded role_permissions rows: 56 admin + 22 landlord + 12 tenant
// + 10 buyer = 100 rows. Keep every grant next to its role; a grant nobody
// holds is not a grant.
//
// NOTE for editors: check-permission-parity scans this file for quoted
// snake_case strings and requires each one to be a seeded permission. Do not
// put any other snake_case word in quotes here (use plain words instead).
import type { AppRole } from "./roles.ts";
import type { PermissionSlug } from "./slug.ts";

export const PERMISSION_GROUPS = [
  "properties",
  "units",
  "owners",
  "contracts",
  "money",
  "maintenance",
  "documents",
  "notices",
  "disputes",
  "platform",
] as const;
export type PermissionGroup = (typeof PERMISSION_GROUPS)[number];

export const GROUP_OF_PERMISSION: Record<PermissionSlug, PermissionGroup> = {
  property_read_public: "properties",
  property_create: "properties",
  property_update_own: "properties",
  property_update_any: "properties",
  property_submit: "properties",
  property_publish: "properties",
  property_withdraw: "properties",
  property_delete: "properties",
  unit_read: "units",
  unit_create: "units",
  unit_update_own: "units",
  unit_update_any: "units",
  owner_read_own: "owners",
  owner_read_any: "owners",
  owner_register: "owners",
  owner_update_own: "owners",
  owner_update_any: "owners",
  owner_kyc_approve: "owners",
  contract_read_own: "contracts",
  contract_read_any: "contracts",
  contract_create: "contracts",
  contract_update: "contracts",
  contract_suspend: "contracts",
  contract_terminate: "contracts",
  contract_renew: "contracts",
  payment_read_own: "money",
  payment_read_any: "money",
  payment_create_own: "money",
  payment_create_any: "money",
  payment_refund: "money",
  payout_read_own: "money",
  payout_run: "money",
  payout_approve: "money",
  payout_initiate: "money",
  ticket_create_own: "maintenance",
  ticket_read_own: "maintenance",
  ticket_read_any: "maintenance",
  ticket_manage: "maintenance",
  ticket_approve_cost: "maintenance",
  document_read_own: "documents",
  document_read_any: "documents",
  document_upload: "documents",
  document_generate: "documents",
  document_release: "documents",
  notice_read_own: "notices",
  notice_send: "notices",
  dispute_create: "disputes",
  dispute_read_own: "disputes",
  dispute_read_any: "disputes",
  dispute_resolve: "disputes",
  saved_search_manage: "platform",
  admin_dashboard_read: "platform",
  client_filter_manage: "platform",
  user_manage: "platform",
  audit_read: "platform",
  settings_manage: "platform",
};

export const GRANTS: Record<AppRole, readonly PermissionSlug[]> = {
  admin: [
    "property_read_public",
    "property_create",
    "property_update_own",
    "property_update_any",
    "property_submit",
    "property_publish",
    "property_withdraw",
    "property_delete",
    "unit_read",
    "unit_create",
    "unit_update_own",
    "unit_update_any",
    "owner_read_own",
    "owner_read_any",
    "owner_register",
    "owner_update_own",
    "owner_update_any",
    "owner_kyc_approve",
    "contract_read_own",
    "contract_read_any",
    "contract_create",
    "contract_update",
    "contract_suspend",
    "contract_terminate",
    "contract_renew",
    "payment_read_own",
    "payment_read_any",
    "payment_create_own",
    "payment_create_any",
    "payment_refund",
    "payout_read_own",
    "payout_run",
    "payout_approve",
    "payout_initiate",
    "ticket_create_own",
    "ticket_read_own",
    "ticket_read_any",
    "ticket_manage",
    "ticket_approve_cost",
    "document_read_own",
    "document_read_any",
    "document_upload",
    "document_generate",
    "document_release",
    "notice_read_own",
    "notice_send",
    "dispute_create",
    "dispute_read_own",
    "dispute_read_any",
    "dispute_resolve",
    "saved_search_manage",
    "admin_dashboard_read",
    "client_filter_manage",
    "user_manage",
    "audit_read",
    "settings_manage",
  ],
  landlord: [
    "property_read_public",
    "property_create",
    "property_update_own",
    "property_submit",
    "property_withdraw",
    "unit_read",
    "unit_create",
    "unit_update_own",
    "owner_read_own",
    "owner_register",
    "owner_update_own",
    "contract_read_own",
    "payment_read_own",
    "payout_read_own",
    "ticket_create_own",
    "ticket_read_own",
    "document_read_own",
    "document_upload",
    "notice_read_own",
    "dispute_create",
    "dispute_read_own",
    "saved_search_manage",
  ],
  tenant: [
    "property_read_public",
    "unit_read",
    "contract_read_own",
    "payment_read_own",
    "payment_create_own",
    "ticket_create_own",
    "ticket_read_own",
    "document_read_own",
    "notice_read_own",
    "dispute_create",
    "dispute_read_own",
    "saved_search_manage",
  ],
  buyer: [
    "property_read_public",
    "unit_read",
    "contract_read_own",
    "payment_read_own",
    "payment_create_own",
    "document_read_own",
    "notice_read_own",
    "dispute_create",
    "dispute_read_own",
    "saved_search_manage",
  ],
};

export function grantsFor(role: AppRole): readonly PermissionSlug[] {
  return GRANTS[role];
}

export function grantsInclude(role: AppRole, permission: PermissionSlug): boolean {
  return GRANTS[role].includes(permission);
}
