// permissions/slug.ts — the 56 permission slugs (docs/07 §2.1).
// Slugs are the stable identifiers shared by role_permissions rows, RLS policies
// (private.has_permission) and requirePermission calls. Keep the list sorted;
// check-permission-parity compares it against the seeded rows.
import { z } from "zod";

export const PERMISSION_SLUGS = [
  "admin_dashboard_read",
  "audit_read",
  "client_filter_manage",
  "contract_create",
  "contract_read_any",
  "contract_read_own",
  "contract_renew",
  "contract_suspend",
  "contract_terminate",
  "contract_update",
  "dispute_create",
  "dispute_read_any",
  "dispute_read_own",
  "dispute_resolve",
  "document_generate",
  "document_read_any",
  "document_read_own",
  "document_release",
  "document_upload",
  "notice_read_own",
  "notice_send",
  "owner_kyc_approve",
  "owner_read_any",
  "owner_read_own",
  "owner_register",
  "owner_update_any",
  "owner_update_own",
  "payment_create_any",
  "payment_create_own",
  "payment_read_any",
  "payment_read_own",
  "payment_refund",
  "payout_approve",
  "payout_initiate",
  "payout_read_own",
  "payout_run",
  "property_create",
  "property_delete",
  "property_publish",
  "property_read_public",
  "property_submit",
  "property_update_any",
  "property_update_own",
  "property_withdraw",
  "saved_search_manage",
  "settings_manage",
  "ticket_approve_cost",
  "ticket_create_own",
  "ticket_manage",
  "ticket_read_any",
  "ticket_read_own",
  "unit_create",
  "unit_read",
  "unit_update_any",
  "unit_update_own",
  "user_manage",
] as const;
export type PermissionSlug = (typeof PERMISSION_SLUGS)[number];
export const PermissionSlug = z.enum(PERMISSION_SLUGS);
