// asset.ts — public tables for the asset area. Mirrors the SQL migrations column for column.
// The migrations are the DDL source of truth; this file exists so TypeScript
// queries are typed. Referential structure lives in relations.ts (this file
// declares no .references(), so the seven schema modules stay cycle-free).
// Column parity with information_schema is enforced by test/schema-parity/test.ts.

import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  char,
  date,
  integer,
  jsonb,
  numeric,
  pgTable,
  smallint,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core";
import {
  allocationSaleStatusEnum,
  kycStatusEnum,
  listingTypeEnum,
  mediaKindEnum,
  ownerTypeEnum,
  propertyStatusEnum,
  propertyTypeEnum,
  titleTypeEnum,
  topographyEnum,
  unitStatusEnum,
} from "../enums.ts";

export const owners = pgTable("owners", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  reference: text("reference").unique().notNull(),
  userId: uuid("user_id").unique(),
  ownerType: ownerTypeEnum("owner_type").notNull(),
  legalName: text("legal_name").notNull(),
  businessName: text("business_name"),
  email: text("email"),
  phoneE164: text("phone_e164"),
  address: text("address"),
  rcNumber: text("rc_number"),
  kycStatus: kycStatusEnum("kyc_status").default("not_started").notNull(),
  kycNotes: text("kyc_notes"),
  kycReviewedBy: uuid("kyc_reviewed_by"),
  kycReviewedAt: timestamp("kyc_reviewed_at", { withTimezone: true, mode: "date" }),
  pep: boolean("pep").default(false).notNull(),
  managementFeeBps: integer("management_fee_bps").default(1000).notNull(),
  commissionBps: integer("commission_bps").default(500).notNull(),
  isActive: boolean("is_active").default(true).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).defaultNow().notNull(),
});

export const properties = pgTable("properties", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  reference: text("reference").unique().notNull(),
  slug: text("slug").unique().notNull(),
  title: text("title").notNull(),
  description: text("description").default("").notNull(),
  listingType: listingTypeEnum("listing_type").notNull(),
  propertyType: propertyTypeEnum("property_type").notNull(),
  status: propertyStatusEnum("status").default("draft").notNull(),
  ownerId: uuid("owner_id").notNull(),
  addressLine1: text("address_line1").notNull(),
  addressLine2: text("address_line2"),
  city: text("city").notNull(),
  lga: text("lga").notNull(),
  state: text("state").notNull(),
  country: char("country", { length: 2 }).default("NG").notNull(),
  latitude: numeric("latitude", { precision: 9, scale: 6 }),
  longitude: numeric("longitude", { precision: 9, scale: 6 }),
  bedrooms: smallint("bedrooms"),
  bathrooms: smallint("bathrooms"),
  toilets: smallint("toilets"),
  parkingSpaces: smallint("parking_spaces").default(0).notNull(),
  sizeSqm: numeric("size_sqm", { precision: 10, scale: 2 }),
  sizePlot: numeric("size_plot", { precision: 10, scale: 2 }),
  yearBuilt: smallint("year_built"),
  isFurnished: boolean("is_furnished").default(false).notNull(),
  isShared: boolean("is_shared").default(false).notNull(),
  isCorner: boolean("is_corner").default(false).notNull(),
  isGated: boolean("is_gated").default(false).notNull(),
  has24hPower: boolean("has_24h_power").default(false).notNull(),
  hasBorehole: boolean("has_borehole").default(false).notNull(),
  hasElevator: boolean("has_elevator").default(false).notNull(),
  hasGenerator: boolean("has_generator").default(false).notNull(),
  hasSwimmingPool: boolean("has_swimming_pool").default(false).notNull(),
  hasGas: boolean("has_gas").default(false).notNull(),
  amenities: text("amenities").array().default(sql`'{}'::text[]`).notNull(),
  maxPriceKobo: bigint("max_price_kobo", { mode: "number" }),
  priceKobo: bigint("price_kobo", { mode: "number" }).notNull(),
  priceCadence: text("price_cadence").default("outright").notNull(),
  negotiable: boolean("negotiable").default(false).notNull(),
  coverPhotoPublicId: text("cover_photo_public_id"),
  publishedAt: timestamp("published_at", { withTimezone: true, mode: "date" }),
  withdrawnAt: timestamp("withdrawn_at", { withTimezone: true, mode: "date" }),
  soldAt: timestamp("sold_at", { withTimezone: true, mode: "date" }),
  archivedAt: timestamp("archived_at", { withTimezone: true, mode: "date" }),
  createdBy: uuid("created_by"),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).defaultNow().notNull(),
  deletedAt: timestamp("deleted_at", { withTimezone: true, mode: "date" }),
});

export const propertyMedia = pgTable(
  "property_media",
  {
    id: uuid("id").primaryKey().defaultRandom().notNull(),
    propertyId: uuid("property_id").notNull(),
    publicId: text("public_id").unique().notNull(),
    kind: mediaKindEnum("kind").default("image").notNull(),
    sortOrder: smallint("sort_order").default(0).notNull(),
    altText: text("alt_text").notNull(),
    width: integer("width"),
    height: integer("height"),
    byteSize: integer("byte_size"),
    format: text("format"),
    blurhash: text("blurhash"),
    isCover: boolean("is_cover").default(false).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).defaultNow().notNull(),
  },
  (table) => [
    unique("property_media_property_id_public_id_key").on(table.propertyId, table.publicId),
  ],
);

export const landDetails = pgTable("land_details", {
  propertyId: uuid("property_id").primaryKey().notNull(),
  sizeSqm: numeric("size_sqm", { precision: 12, scale: 2 }).notNull(),
  sizePlot: numeric("size_plot", { precision: 10, scale: 2 }),
  plotCount: smallint("plot_count"),
  topography: topographyEnum("topography").default("flat").notNull(),
  titleType: titleTypeEnum("title_type").default("unregistered").notNull(),
  titleDocumentReference: text("title_document_reference"),
  gazetteReference: text("gazette_reference"),
  surveyPlanPublicId: text("survey_plan_public_id"),
  allocationLetterPublicId: text("allocation_letter_public_id"),
  blockAndPlot: text("block_and_plot"),
  latitude: numeric("latitude", { precision: 9, scale: 6 }),
  longitude: numeric("longitude", { precision: 9, scale: 6 }),
  boundaryGeojson: jsonb("boundary_geojson").$type<Record<string, unknown>>(),
  siteAccessNote: text("site_access_note"),
  isAllocated: boolean("is_allocated").default(false).notNull(),
  isCornerPlot: boolean("is_corner_plot").default(false).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).defaultNow().notNull(),
});

export const units = pgTable(
  "units",
  {
    id: uuid("id").primaryKey().defaultRandom().notNull(),
    propertyId: uuid("property_id").notNull(),
    code: text("code").notNull(),
    floor: smallint("floor"),
    bedrooms: smallint("bedrooms"),
    bathrooms: smallint("bathrooms"),
    toilets: smallint("toilets"),
    sizeSqm: numeric("size_sqm", { precision: 10, scale: 2 }),
    askingRentKobo: bigint("asking_rent_kobo", { mode: "number" }),
    serviceChargeKobo: bigint("service_charge_kobo", { mode: "number" }).default(0).notNull(),
    status: unitStatusEnum("status").default("vacant").notNull(),
    currentContractId: uuid("current_contract_id"),
    availableFrom: date("available_from", { mode: "date" }),
    notes: text("notes"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).defaultNow().notNull(),
  },
  (table) => [unique("units_property_id_code_key").on(table.propertyId, table.code)],
);

export const saleAllocations = pgTable("sale_allocations", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  reference: text("reference").unique().notNull(),
  propertyId: uuid("property_id").notNull(),
  buyerId: uuid("buyer_id"),
  buyerName: text("buyer_name").notNull(),
  buyerPhoneE164: text("buyer_phone_e164"),
  plotLabel: text("plot_label").default("Entire parcel").notNull(),
  sizeSqm: numeric("size_sqm", { precision: 12, scale: 2 }),
  sizePlot: numeric("size_plot", { precision: 10, scale: 2 }),
  priceKobo: bigint("price_kobo", { mode: "number" }).notNull(),
  depositPaidKobo: bigint("deposit_paid_kobo", { mode: "number" }).default(0).notNull(),
  contractId: uuid("contract_id"),
  status: allocationSaleStatusEnum("status").default("proposed").notNull(),
  allocatedAt: timestamp("allocated_at", { withTimezone: true, mode: "date" }),
  releasedAt: timestamp("released_at", { withTimezone: true, mode: "date" }),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).defaultNow().notNull(),
});
